[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
arcium_matching = "CgsWgvD6wepEsfxvrHexdSv77m3AvP3vdd4zH2D6Vewa"

[programs.devnet]
arcium_matching = "4pugEiQsBghERnjwM6z9yrTPrGjwrzzwuV6cNP2hHqZF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/mnt/c/Users/Spektor/documents/cysh/programs/arcium-matching/artifacts/arcium_program_0.3.0.so"
