[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
settlement = "HkamtrV1uGYGHgL8rZxmXubtnLawS3yiizCBQXCpiZds"

[programs.devnet]
settlement = "HkamtrV1uGYGHgL8rZxmXubtnLawS3yiizCBQXCpiZds"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '~/.config/solana/id.json'

[scripts]
test = "pnpm --dir tests exec ts-mocha -p ./tsconfig.json -t 1000000 token22-swap.test.ts"
